(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'comment'"
p3
sS'layer'
p4
S'E:\\web2py\\applications\\reddit_clone\\controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 08129188, file "E:\\web2py\\applications\\reddit_clone\\controllers/default.py", line 17>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "E:\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "E:\\web2py\\applications\\reddit_clone\\controllers/default.py", line 133, in <module>\n  File "E:\\web2py\\gluon\\globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "E:\\web2py\\applications\\reddit_clone\\controllers/default.py", line 70, in view_post\n    comments = db(db.comment.post == post.id).select(orderby=~db.comm.created_on)\n  File "C:\\Python27\\lib\\site-packages\\pydal\\base.py", line 669, in __getattr__\n    return BasicStorage.__getattribute__(self, key)\nAttributeError: \'DAL\' object has no attribute \'comment\'\n'
p11
s.